### ISSUE TITLE
Problem with the documentation

### ISSUE THREAD

**Issue by Awesomewsdm** [hubtel/hubtel-mobile-flutter-merchant-checkout-sdk#6]
```yaml
  hubtel_merchant_checkout_sdk:
    git:
      url: https://github.com/hubtel/hubtel-mobile-flutter-merchant-checkout-sdk.git
      ref: main
```
ref is supposed to be master not main
